/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lightoff_francois_version_console;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Scanner;
import javax.swing.JButton;

/**
 *
 * @author Tanguy
 */
public class FenetrePrincipale extends javax.swing.JFrame {

    GrilleDeJeu grille;
    int nbCoups;
    int nbCoupsMax;

    /**
     * Creates new form FenetrePrincipale
     */
    public FenetrePrincipale() {
        initComponents();

        int nbLignes = 15;
        int nbColonnes = 15;
        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, nbColonnes * 40, nbLignes * 40));
        this.pack();
        this.revalidate();
        PanneauBoutonsVerticaux.setLayout(new GridLayout(nbLignes, 1));
        getContentPane().add(PanneauBoutonsVerticaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1 * 40, nbLignes * 40));
        this.pack();
        this.revalidate();

        btndiagD.setLayout(new GridLayout(1, 1));
        getContentPane().add(btndiagD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20,  40, 40));
        this.pack();
        this.revalidate();
        JButton bouton_diagD = new JButton();
            ActionListener ecouteurClickDiagD = new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    grille.activerDiagonaleDescendante(0,0);
                    repaint();
                }
            };
            bouton_diagD.addActionListener(ecouteurClickDiagD);
            btndiagD.add(bouton_diagD);
            
            
        btndiagM.setLayout(new GridLayout(1, 1));
        getContentPane().add(btndiagM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60+nbColonnes*40, 20,  40, 40));
        this.pack();
        this.revalidate();
        JButton bouton_diagM = new JButton();
            ActionListener ecouteurClickDiagM = new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    grille.activerDiagonaleMontante(0,0);
                    repaint();
                }
            };
            bouton_diagM.addActionListener(ecouteurClickDiagM);
            btndiagM.add(bouton_diagM);    

        PanneauBoutonsHorizontaux.setLayout(new GridLayout(1, nbColonnes));
        getContentPane().add(PanneauBoutonsHorizontaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, nbColonnes * 40, 1 * 40));
        this.pack();
        this.revalidate();
        for (int i = 0; i < nbColonnes; i++) {
            final int j = i;
            JButton bouton_ligne = new JButton();
            ActionListener ecouteurClick = new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    grille.activerColonneDeCellules(j);
                    repaint();
                }
            };
            bouton_ligne.addActionListener(ecouteurClick);
            PanneauBoutonsHorizontaux.add(bouton_ligne);
        }

        for (int i = 0; i < nbLignes; i++) {
            final int j = i;
            JButton bouton_ligne = new JButton();
            ActionListener ecouteurClick = new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    grille.activerLigneDeCellules(j);
                    repaint();
                }
            };
            bouton_ligne.addActionListener(ecouteurClick);
            PanneauBoutonsVerticaux.add(bouton_ligne);
        }

        this.grille = new GrilleDeJeu(nbLignes, nbColonnes);
        PanneauGrille.setLayout(new GridLayout(nbLignes, nbColonnes));
        initialiserPartie();
        for (int i = 0; i < nbLignes; i++) {
            for (int j = 0; j < nbColonnes; j++) {
                CelluleGraphique bouton_cellule = new CelluleGraphique(grille.matriceCellules[i][j], 36, 36); // création d'un bouton
                PanneauGrille.add(bouton_cellule); // ajout au Jpanel PanneauGrille

            }
        }

    }

    public void initialiserPartie() {
        grille.eteindreToutesLesCellules();
        grille.genererMatriceAleatoire(10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrille = new javax.swing.JPanel();
        btnDiagonaleM = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PanneauBoutonsVerticaux = new javax.swing.JPanel();
        PanneauBoutonsHorizontaux = new javax.swing.JPanel();
        btndiagD = new javax.swing.JPanel();
        btndiagM = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout PanneauGrilleLayout = new javax.swing.GroupLayout(PanneauGrille);
        PanneauGrille.setLayout(PanneauGrilleLayout);
        PanneauGrilleLayout.setHorizontalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        PanneauGrilleLayout.setVerticalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 360, 360));

        btnDiagonaleM.setText("jButton1");
        btnDiagonaleM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagonaleMActionPerformed(evt);
            }
        });
        getContentPane().add(btnDiagonaleM, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 70, 60));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 380, 100));

        PanneauBoutonsVerticaux.setBackground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout PanneauBoutonsVerticauxLayout = new javax.swing.GroupLayout(PanneauBoutonsVerticaux);
        PanneauBoutonsVerticaux.setLayout(PanneauBoutonsVerticauxLayout);
        PanneauBoutonsVerticauxLayout.setHorizontalGroup(
            PanneauBoutonsVerticauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        PanneauBoutonsVerticauxLayout.setVerticalGroup(
            PanneauBoutonsVerticauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauBoutonsVerticaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 80, 360));

        PanneauBoutonsHorizontaux.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout PanneauBoutonsHorizontauxLayout = new javax.swing.GroupLayout(PanneauBoutonsHorizontaux);
        PanneauBoutonsHorizontaux.setLayout(PanneauBoutonsHorizontauxLayout);
        PanneauBoutonsHorizontauxLayout.setHorizontalGroup(
            PanneauBoutonsHorizontauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        PanneauBoutonsHorizontauxLayout.setVerticalGroup(
            PanneauBoutonsHorizontauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauBoutonsHorizontaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 360, 60));

        btndiagD.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout btndiagDLayout = new javax.swing.GroupLayout(btndiagD);
        btndiagD.setLayout(btndiagDLayout);
        btndiagDLayout.setHorizontalGroup(
            btndiagDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        btndiagDLayout.setVerticalGroup(
            btndiagDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(btndiagD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 80, 60));

        btndiagM.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout btndiagMLayout = new javax.swing.GroupLayout(btndiagM);
        btndiagM.setLayout(btndiagMLayout);
        btndiagMLayout.setHorizontalGroup(
            btndiagMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        btndiagMLayout.setVerticalGroup(
            btndiagMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(btndiagM, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDiagonaleMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagonaleMActionPerformed
        this.grille.activerDiagonaleMontante(0, 0);
        gagné();
        repaint();

    }//GEN-LAST:event_btnDiagonaleMActionPerformed
    public void gagné() {
        nbCoups += 1;

        if (grille.cellulesToutesEteintes() == true) {
            jLabel1.setText("Bravo vous avez gagné au bout de " + nbCoups + " coups");
            btnLigne0.setEnabled(false);
            btnLigne1.setEnabled(false);
            btnLigne2.setEnabled(false);
            btnLigne3.setEnabled(false);
            btnLigne4.setEnabled(false);
            btnLigne5.setEnabled(false);
            btnLigne6.setEnabled(false);
            btnLigne7.setEnabled(false);
            btnLigne8.setEnabled(false);
            btnLigne9.setEnabled(false);
            btnColonne0.setEnabled(false);
            btnColonne1.setEnabled(false);
            btnColonne2.setEnabled(false);
            btnColonne3.setEnabled(false);
            btnColonne4.setEnabled(false);
            btnColonne5.setEnabled(false);
            btnColonne6.setEnabled(false);
            btnColonne7.setEnabled(false);
            btnColonne8.setEnabled(false);
            btnColonne9.setEnabled(false);
            btnDiagonaleM.setEnabled(false);
            btnDiagonaleD.setEnabled(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FenetrePrincipale().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauBoutonsHorizontaux;
    private javax.swing.JPanel PanneauBoutonsVerticaux;
    private javax.swing.JPanel PanneauGrille;
    private javax.swing.JButton btnDiagonaleM;
    private javax.swing.JPanel btndiagD;
    private javax.swing.JPanel btndiagM;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
